In [37]:
import numpy as np

In [38]:
a = np.array([1,2,3,4])
print(type(a))   # <class 'numpy.ndarray'>
print(a.shape)   # (4, )

<class 'numpy.ndarray'>
(4,)


In [39]:
b = np.array([[1, 2, 3, 4], [5,6,7,8]])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [40]:
b.T   # give transpose of b

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [41]:
np.dot(b, b.T)

array([[ 30,  70],
       [ 70, 174]])

In [42]:
# np.random.randint?
matrix = np.random.randint(60, 100, (5, 5))

In [43]:
print(matrix)

[[97 98 68 62 96]
 [95 67 81 71 82]
 [73 85 84 70 73]
 [99 70 63 95 88]
 [87 88 77 76 86]]


In [44]:
print(np.max(matrix))
print(np.min(matrix))

99
62


In [45]:
a = np.array([0,1,2,-8,6,8,10])

In [46]:
np.argmin(a)     # return index of min element

3

In [47]:
b = np.array([0, 1, 10, 10, 2, -8, 6, 6, 6, 6, 8, 10])

In [48]:
print(np.unique(b))


[-8  0  1  2  6  8 10]


In [49]:
print(np.unique(b, return_counts=True))

(array([-8,  0,  1,  2,  6,  8, 10]), array([1, 1, 1, 1, 4, 1, 3], dtype=int64))


In [50]:
c = np.unique(b, return_counts=True)
print(c)

(array([-8,  0,  1,  2,  6,  8, 10]), array([1, 1, 1, 1, 4, 1, 3], dtype=int64))


In [51]:
print(c[0])

[-8  0  1  2  6  8 10]


In [52]:
print(c[1])

[1 1 1 1 4 1 3]


In [53]:
# Program to find out the number with the highest frequency in the array
d = np.unique(b, return_counts=True)
print(d)

(array([-8,  0,  1,  2,  6,  8, 10]), array([1, 1, 1, 1, 4, 1, 3], dtype=int64))


In [56]:
idx = np.argmax(d[1])
ele = d[0][idx]
print(ele)

6


In [57]:
# Slicing Arrays
matrix

array([[97, 98, 68, 62, 96],
       [95, 67, 81, 71, 82],
       [73, 85, 84, 70, 73],
       [99, 70, 63, 95, 88],
       [87, 88, 77, 76, 86]])

In [59]:
matrix[2:4, 2:5]

array([[84, 70, 73],
       [63, 95, 88]])