Working with Numpy - for mathematical operations

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(5,)


In [4]:
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [5]:
print(b[0][0])

1


In [6]:
c = np.array([[1,2,3], [4,5,6]])
print(c)
print(c.shape)
print(c[1,1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [7]:
# Create Zeros, Ones,Custom array
a = np.zeros((3, 3))
print(a)

b = np.ones((2, 3))
print(b)

# Array of some constants
c = np.full((3,2), 5)
print(c)

# Identity Matrix - Size / Square matrix
d = np.eye(4)
print(d)

# Random Matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.90015383 0.62624404 0.4333568 ]
 [0.77018284 0.93050718 0.66589638]]


In [8]:
print(randomMatrix[ : , 1])

[0.62624404 0.93050718]


In [9]:
randomMatrix[1, 1:] = 1
print(randomMatrix)

[[0.90015383 0.62624404 0.4333568 ]
 [0.77018284 1.         1.        ]]


In [10]:
# Set some rows and columns with any values
z = np.zeros((3,3), dtype=np.int64)
print(z)
z[1, : ] = 5
z[ : , -1] = 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [11]:
# Datatypes
print(z.dtype)

int64


In [12]:
# Mathematical Operations

x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(x + y)
print(np.add(x,y))
print(x - y)
print(np.subtract(x,y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [13]:
# Matrix Multiplication / Dot Products
print(x)
print(y)
print(x.dot(y))
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [14]:
# Multiplication of Vectors
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [15]:
# Sum 
print(a)

[1 2 3 4]


In [16]:
print(sum(a))

10


In [17]:
print(x)

[[1 2]
 [3 4]]


In [18]:
print(np.sum(x))
print(np.sum(x, axis = 0))  # sum of columns
print(np.sum(x, axis = 1))  # sum of rows

10
[4 6]
[3 7]


In [19]:
# Stacking of Arrays
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [20]:
b = b**2
print(b)

[ 1  4  9 16]


In [21]:
a = np.stack((a,b), axis = 0)

In [22]:
# Reshape a Numpy Array
# a = np.stack((a,b), axis = 1)
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [23]:
a = a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [24]:
a = a.reshape(8,)
print(a)

[ 1  2  3  4  1  4  9 16]


In [26]:
a = a.reshape(4,-1)
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
