## Numpy Random Module

##### rand : random valures in a given shape
##### randn : return a sample(or samples) from the "standard normal" distribution.
##### randint : return random integers from low (inclusive) to high (exclusive)
##### random : return random floats in the half-open interval [0.0, 1.0]
##### choice: generates a random sample fro a goven 1-D array
##### Shuffle: shuffles the contents of a sequence

In [14]:
import numpy as np

In [15]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
np.random.seed(1)

a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [17]:
np.random.shuffle(a)
print(a)

[ 7 14 11  9  5  8  6 12 13 10]


In [18]:
# Returns value from a Standard Normal Distribution
a = np.random.rand(2, 3)

In [19]:
print(a)

[[0.38791074 0.66974604 0.93553907]
 [0.84631092 0.31327352 0.52454816]]


In [20]:
a = np.random.randint(5,10,2)
print(a)

[9 7]


In [21]:
# Randomly pick one element from an array
element = np.random.choice([1, 2, 4, 3, 11, 27])
print(element)

11
