# Some More Numpy Functions - Statistics

##### min, max
##### mean, median
##### average
##### variance
##### standard deviation

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4], [7,6,2,0]])
print(a)
print(np.min(a))
print(np.min(a, axis=0))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]


In [4]:
print(np.max(a))
# Specify axis for the direction in multidirection array
print(np.max(a, axis=1))

7
[4 7]


In [5]:
np.mean(a)

3.125

In [6]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [7]:
c = np.array([1,2,3,4,5])
d = np.array([1,2,3,4,5,6])
print(np.median(c))
print(np.median(d))

3.0
3.5


In [10]:
# Mean vs Average
print(np.mean(c))

w = np.array([1,1,1,4,5])
print(np.average(c, weights=w))

3.0
3.9166666666666665


In [11]:
# Standard Deviation
'''
sigma = under root(1/N * summation i=1 to N (xi - mu)**2)
'''
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

1.4142135623730951


In [12]:
dev = np.std(c)
print(dev)

1.4142135623730951


In [14]:
# Variance 
print(myStd**2)
print(np.var(c))

2.0000000000000004
2.0
