In [5]:
''' 
Given a running stream of numbers, compute mean and variance at any given point.
'''

' \nGiven a running stream of numbers, compute mean and variance at any given point.\n'

In [1]:
import numpy as np

In [3]:
# n = int(input())
a = list(int(i) for i in input().strip().split())
a = np.array(a)
print(a)
print(type(a))
Mean = np.mean(a)
Variance = np.var(a)
print(Mean)
print(Variance)

[1 2 3 4 5]
<class 'numpy.ndarray'>
3.0
2.0


In [8]:
a = [[1,2,3], [4,5,6], [7,8,9]]
print(np.ravel(a))

[1 2 3 4 5 6 7 8 9]


In [19]:
a = np.random.randint(0, 15, size=(4,4))
a = a[((a>=5) & (a<=10))]
print(a)

[5 9 7]


In [22]:
a = np.arange(1,17).reshape(4,4)
b = np.arange(17,33).reshape(4,4)
c = np.concatenate((a,b), axis = 1)
print(c)

[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]
